"""Add visibility field to notes/posts

Revision ID: 0e75eb0b94c5
Revises: 66e212d2f45b
Create Date: 2025-07-30 20:02:57.383573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e75eb0b94c5'
down_revision = '66e212d2f45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('private_note', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
