"""Add ondelete cascade to foreign keys

Revision ID: 54ff1f94842e
Revises: 4f17daffbf38
Create Date: 2025-08-07 17:02:19.582066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ff1f94842e'
down_revision = '4f17daffbf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('like_table_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('like_table_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('private_notes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('private_notes_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('saved_posts_post_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('saved_posts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_posts_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('saved_posts_post_id_fkey'), 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('private_notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('private_notes_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('like_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('like_table_post_id_fkey'), 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('like_table_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
