"""Fixed

Revision ID: 6b773d69f384
Revises: 
Create Date: 2025-07-22 19:48:46.170312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b773d69f384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tags', sa.VARCHAR(length=30), nullable=True),
    sa.Column('visibility', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('profile_picture', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
